# Generated by Django 3.1 on 2021-01-15 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='penyakit_bawaan',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='dilaporkan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilaporkan', to=settings.AUTH_USER_MODEL, to_field='nomor_induk'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelapor', to=settings.AUTH_USER_MODEL, to_field='nomor_induk'),
        ),
        migrations.CreateModel(
            name='RiwayatPenyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayat', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='nomor_induk')),
            ],
        ),
    ]
