# Generated by Django 3.1 on 2021-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210113_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status_laporan',
            field=models.CharField(max_length=32),
        ),
    ]
