# Generated by Django 3.1 on 2021-01-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210116_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riwayatpenyakit',
            old_name='user',
            new_name='dilaporkan',
        ),
    ]
