# Generated by Django 3.1 on 2021-01-20 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210119_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='pelapor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelapor', to=settings.AUTH_USER_MODEL, to_field='nomor_induk'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status_laporan',
            field=models.CharField(default='Belum Ditangani', max_length=32),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_laporan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
