# Generated by Django 3.1 on 2021-01-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210113_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='lapor_pusat',
            field=models.BooleanField(default=False),
        ),
    ]
