# Generated by Django 3.1 on 2021-01-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210120_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status_laporan',
            field=models.CharField(blank=True, default='Menunggu penanganan', max_length=32),
        ),
    ]
